version: "3.7"
services:
  discord-bot:
    container_name: uni-bot-dev.local
    # command: modd # Hot reloading
    build: .
    ports:
      - 8888:80
    ## Vars to put in override:
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - CANVAS_DOMAIN=${CANVAS_DOMAIN}
      - SCHEDULER_TRIGGER=${SCHEDULER_TRIGGER}
    volumes:
      - "./config:/config"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 500M
        reservations:
          cpus: "0.25"
          memory: 200M
